# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: ./src/CalculatorLibrary
  displayName: 'Build Calculator Library'

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: ./src/Calculator
  displayName: 'Build Calculator Web API'

- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test --results-directory TestResults --logger:trx
  workingDirectory: ./src/CalculatorTest
  displayName: 'Build and run tests'

- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: './TestResults/*.trx' 
    buildConfiguration: $(buildConfiguration))
